#!/usr/bin/env bash
# Script that transfers file to server
if [ $# -lt 4 ]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   path=$1
   ip=$2
   username=$3
   key=$4
   scp -o "StrictHostKeyChecking=no" -i $key $path $username@$ip:~/
fi
