#!/usr/bin/env bash
# make a 404 error page

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo "Hello World" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
" > /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ]
then
    service nginx start
else
    service nginx restart
fi
