#!/usr/bin/env bash
# get nginx to listen on port 80 for all sites
apt install -y nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
