#!/usr/bin/env bash
terminator() {

  rm /var/run/holbertonscript.pid

  exit

}



echo "$$" > /var/run/holbertonscript.pid



while true

do

  echo "To infinity and beyond"

  sleep 2

  trap 'echo "Y U no love me?!"' SIGINT

  trap 'echo "I hate the kill command" && terminator' SIGTERM

  trap 'terminator' SIGQUIT

done
